#!/usr/bin/env bash
#
# setup-routines.sh — register the autonomous-loop routines in Hermes.
#
# Idempotent: re-running removes the existing jobs (by name) first, so it never
# creates duplicates. Creates 5 routines:
#   1. "agentic-trading health watch"     — ACTIVE, hourly, no-LLM loop watchdog.
#   2. "agentic-trading pr review"        — ACTIVE, 30m, no-LLM poll → Claude Opus
#                                            4.8 reviews auto/* draft PRs.
#   3. "agentic-trading promote reminder" — ACTIVE, Sun 19:30, no-LLM nudge.
#   4. "agentic-trading nightly improve"  — created then PAUSED. Implements one
#      backlog item in an isolated worktree and opens a DRAFT PR (never merges).
#   5. "agentic-trading weekly research"  — created then PAUSED. Researches +
#      drafts proposals → Claude approves/ranks → weekly patch notes.
#
# Resume the two paused jobs only after a supervised first run (see the bottom).
# Delivery: telegram (via HERMES_DELIVER in loop.env), matching your other routines.

set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
HSCRIPTS="$HOME/.hermes/scripts"
export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"

# Host config (delivery target etc.) — gitignored; see loop.env.example.
[ -f "$ROOT/scripts/hermes/loop.env" ] && { set -a; . "$ROOT/scripts/hermes/loop.env"; set +a; }
DELIVER="${HERMES_DELIVER:-}"
if [ -z "$DELIVER" ]; then
  echo "✖ HERMES_DELIVER is not set. Copy scripts/hermes/loop.env.example to" >&2
  echo "  scripts/hermes/loop.env and set HERMES_DELIVER (e.g. telegram:123456789)." >&2
  exit 1
fi

# Locate the hermes CLI (wrapper on PATH, else the venv module).
if command -v hermes >/dev/null 2>&1; then
  HERMES=(hermes)
else
  HERMES=("$HOME/.hermes/hermes-agent/venv/bin/python" -m hermes_cli.main)
fi

# Hermes requires --script files to physically live under ~/.hermes/scripts (it
# rejects symlinks resolving outside it). Install thin wrappers there that exec
# the real, version-controlled repo scripts.
echo "▶ Installing script wrappers into $HSCRIPTS (exec the repo scripts)"
mkdir -p "$HSCRIPTS"
install_wrapper() { # <wrapper-name> <repo-script>
  printf '#!/usr/bin/env bash\n# Auto-generated by agentic-trading setup-routines.sh — execs the repo script.\nexec %q "$@"\n' \
    "$ROOT/scripts/hermes/$2" > "$HSCRIPTS/$1"
  chmod +x "$HSCRIPTS/$1"
}
install_wrapper agentic-trading-health-watch.sh           health-watch.sh
install_wrapper agentic-trading-loop-context.sh           loop-context.sh
install_wrapper agentic-trading-research-context.sh       research-context.sh
install_wrapper agentic-trading-pr-review-poll.sh         pr-review-poll.sh
install_wrapper agentic-trading-sunday-promote-reminder.sh sunday-promote-reminder.sh

# Install the 'merge trading to main' skill into Hermes.
echo "▶ Installing the promote-to-main skill"
mkdir -p "$HOME/.hermes/skills/agentic-trading-promote-to-main"
sed "s|__TRADING_REPO__|$ROOT|g" \
   "$ROOT/scripts/hermes/skills/agentic-trading-promote-to-main/SKILL.md" \
   > "$HOME/.hermes/skills/agentic-trading-promote-to-main/SKILL.md"

# Remove any existing job(s) with a given name, so re-running is idempotent.
remove_by_name() {
  local nm="$1" id
  while :; do
    id="$("${HERMES[@]}" cron list --all 2>/dev/null | awk -v n="$nm" '/\[(active|paused)\]/{id=$1} $0 ~ n {print id; exit}')"
    [ -z "${id:-}" ] && break
    "${HERMES[@]}" cron rm "$id" >/dev/null 2>&1 && echo "  removed existing $nm ($id)" || break
  done
}

# Pause a just-created job by name.
pause_by_name() {
  local nm="$1" id
  id="$("${HERMES[@]}" cron list --all 2>/dev/null | awk -v n="$nm" '/\[(active|paused)\]/{id=$1} $0 ~ n {print id}' | tail -1)"
  if [ -n "${id:-}" ]; then "${HERMES[@]}" cron pause "$id" && echo "  paused $nm ($id)"
  else echo "  ⚠️ could not auto-detect '$nm' — pause manually: hermes cron list --all / hermes cron pause <id>"; fi
}

echo "▶ Creating ACTIVE loop health watchdog (hourly, no LLM)"
remove_by_name "agentic-trading health watch"
"${HERMES[@]}" cron create "every 1h" \
  --name "agentic-trading health watch" \
  --no-agent \
  --script agentic-trading-health-watch.sh \
  --deliver "$DELIVER"

echo "▶ Creating ACTIVE PR-review poll (every 30m; Claude Opus 4.8 reviews auto/* PRs)"
remove_by_name "agentic-trading pr review"
"${HERMES[@]}" cron create "every 30m" \
  --name "agentic-trading pr review" \
  --no-agent \
  --script agentic-trading-pr-review-poll.sh \
  --deliver "$DELIVER"

echo "▶ Creating ACTIVE Sunday promote reminder (Sun 19:30, no LLM)"
remove_by_name "agentic-trading promote reminder"
"${HERMES[@]}" cron create "30 19 * * 0" \
  --name "agentic-trading promote reminder" \
  --no-agent \
  --script agentic-trading-sunday-promote-reminder.sh \
  --deliver "$DELIVER"

echo "▶ Creating nightly improver (3am) — will be PAUSED until you greenlight it"
remove_by_name "agentic-trading nightly improve"
"${HERMES[@]}" cron create "0 3 * * *" "$(cat "$ROOT/scripts/hermes/PROMPT-nightly-improve.md")" \
  --name "agentic-trading nightly improve" \
  --workdir "$ROOT" \
  --script agentic-trading-loop-context.sh \
  --deliver "$DELIVER"
pause_by_name "agentic-trading nightly improve"

echo "▶ Creating weekly research+propose (Mon 7am) — Claude approves/ranks, delivers"
echo "  patch notes. Also PAUSED until greenlit."
remove_by_name "agentic-trading weekly research"
"${HERMES[@]}" cron create "0 7 * * 1" "$(cat "$ROOT/scripts/hermes/PROMPT-weekly-research.md")" \
  --name "agentic-trading weekly research" \
  --workdir "$ROOT" \
  --script agentic-trading-research-context.sh \
  --deliver "$DELIVER"
pause_by_name "agentic-trading weekly research"

cat <<EOF

✓ Routines registered.
  - 'agentic-trading health watch'     : ACTIVE  (hourly loop watchdog)
  - 'agentic-trading pr review'        : ACTIVE  (30m; Claude Opus 4.8 reviews auto/* PRs)
  - 'agentic-trading promote reminder' : ACTIVE  (Sun 19:30 nudge)
  - 'agentic-trading nightly improve'  : PAUSED  (resume after a supervised test run)
  - 'agentic-trading weekly research'  : PAUSED  (research+propose → Claude approves → patch notes)

Supervised first run (recommended before resuming the schedule):
    hermes cron list --all               # find the nightly job id (--all shows PAUSED)
    hermes cron run <id>                 # queue it for the next tick
    hermes cron tick                     # run due jobs once, watch what it does
  Review the draft PR it opens. When satisfied:
    hermes cron resume <id>
EOF
